[rois]
[[rois."Group 1"]]
unique_id = 1
name = "ROI1"
pos_x = 449.65
pos_y = 758.84
size_x = 100.0
size_y = 100.0

[[rois."Group 1"]]
unique_id = 2
name = "ROI2"
pos_x = 664.85
pos_y = 419.19
size_x = 100.0
size_y = 100.0

