[camera1]
address = "DEFAULT_CAMERA_ADDRESS_PLACEHOLDER"

[camera1.ROI."Group 1"]
model_type = "shitu"
model_name = "default_model"
boss1 = [ 224, 385, 100, 100,]

[camera1.ROI."Group 2"]
model_type = "shitu"
model_name = "default_model"
boss2 = [ 477, 33, 100, 100,]

[camera1.ROI."asf Group 3"]
model_type = "default_type"
model_name = "default_model"

[camera1.ROI."Group 3"]
model_type = "default_type"
model_name = "default_model"
ROI4 = [ 506, 533, 100, 100,]
